import { Product, Category, Industry } from './types';

export const categories: Category[] = [
  {
    id: 'dryers',
    slug: 'dryers',
    name: 'Dryers',
    description: 'High-efficiency drying solutions for pharmaceutical and process industries.',
    image: { src: 'https://images.unsplash.com/photo-1581093458791-9d42e3c7e117?w=600&h=400&fit=crop', alt: 'Pharmaceutical Dryers' },
    productCount: 4,
    features: ['Uniform drying', 'Temperature control', 'GMP compliant design', 'Multiple capacity options'],
  },
  {
    id: 'granulators',
    slug: 'granulators',
    name: 'Granulators',
    description: 'Precision granulation equipment for consistent particle size distribution.',
    image: { src: 'https://images.unsplash.com/photo-1581093458791-9d42e3c7e117?w=600&h=400&fit=crop', alt: 'Rapid Mixing Granulator' },
    productCount: 1,
    features: ['High-shear mixing', 'Uniform granules', 'Wet granulation', 'Quick processing'],
  },
  {
    id: 'blenders',
    slug: 'blenders',
    name: 'Blenders',
    description: 'Versatile blending solutions for homogeneous mixing of powders and granules.',
    image: { src: 'https://images.unsplash.com/photo-1581093458791-9d42e3c7e117?w=600&h=400&fit=crop', alt: 'Pharmaceutical Blenders' },
    productCount: 4,
    features: ['Homogeneous mixing', 'Low shear', 'Easy cleaning', 'Multiple geometries'],
  },
  {
    id: 'mixers-mills',
    slug: 'mixers-mills',
    name: 'Mixers & Mills',
    description: 'High-shear mixing and size reduction equipment for various applications.',
    image: { src: 'https://images.unsplash.com/photo-1581093458791-9d42e3c7e117?w=600&h=400&fit=crop', alt: 'Mixers and Mills' },
    productCount: 2,
    features: ['High-shear processing', 'Size reduction', 'Batch processing', 'Robust construction'],
  },
  {
    id: 'coating',
    slug: 'coating',
    name: 'Coating Equipment',
    description: 'Pharmaceutical coating pans for film, sugar, and enteric coating applications.',
    image: { src: 'https://images.unsplash.com/photo-1581093458791-9d42e3c7e117?w=600&h=400&fit=crop', alt: 'Coating Pan' },
    productCount: 1,
    features: ['Uniform coating', 'Pan design', 'Spray system', 'Variable speed'],
  },
  {
    id: 'vessels',
    slug: 'vessels',
    name: 'Process Vessels',
    description: 'Custom fabricated vessels for storage, manufacturing, and mixing applications.',
    image: { src: 'https://images.unsplash.com/photo-1581093458791-9d42e3c7e117?w=600&h=400&fit=crop', alt: 'Process Vessels' },
    productCount: 3,
    features: ['Custom fabrication', 'SS 304/316', 'Various capacities', 'GMP design'],
  },
  {
    id: 'filtration-sifting',
    slug: 'filtration-sifting',
    name: 'Filtration & Sifting',
    description: 'Filtration and sifting equipment for process separation and classification.',
    image: { src: 'https://images.unsplash.com/photo-1581093458791-9d42e3c7e117?w=600&h=400&fit=crop', alt: 'Filtration and Sifting Equipment' },
    productCount: 3,
    features: ['Efficient separation', 'Various mesh sizes', 'Easy maintenance', 'Industrial grade'],
  },
  {
    id: 'liquid-processing',
    slug: 'liquid-processing',
    name: 'Liquid Processing',
    description: 'Complete liquid manufacturing and processing solutions for pharmaceutical and cosmetic industries.',
    image: { src: 'https://images.unsplash.com/photo-1581093458791-9d42e3c7e117?w=600&h=400&fit=crop', alt: 'Liquid Processing Equipment' },
    productCount: 3,
    features: ['Liquid manufacturing', 'Ointment processing', 'Sugar melting', 'GMP compliant'],
  },
  {
    id: 'sterilization',
    slug: 'sterilization',
    name: 'Sterilization Equipment',
    description: 'Sterilization and depyrogenation equipment for pharmaceutical and laboratory applications.',
    image: { src: '/images/products/autoclave.jpg', alt: 'Sterilization Equipment' },
    productCount: 1,
    features: ['Steam sterilization', 'Autoclave systems', 'GMP compliant', 'Lab & production scale'],
  },
  {
    id: 'material-handling',
    slug: 'material-handling',
    name: 'Material Handling',
    description: 'Lifting, transfer, and material handling equipment for pharmaceutical manufacturing.',
    image: { src: '/images/products/lifting-chamber.jpg', alt: 'Material Handling Equipment' },
    productCount: 1,
    features: ['IBC bin systems', 'Lifting chambers', 'Dust-free transfer', 'GMP design'],
  },
  {
    id: 'rnd-equipment',
    slug: 'rnd-equipment',
    name: 'R&D / Lab Equipment',
    description: 'Laboratory and pilot-scale equipment for research, formulation development, and process optimization.',
    image: { src: '/images/products/rnd-equipment.jpg', alt: 'R&D and Lab Equipment' },
    productCount: 5,
    features: ['Lab scale', 'Pilot scale', 'Process development', 'Formulation research'],
  },
];

export const industriesData: Industry[] = [
  {
    id: 'pharmaceutical',
    slug: 'pharmaceutical',
    name: 'Pharmaceutical',
    description: 'GMP-compliant machinery for tablet, capsule, and oral solid dosage manufacturing. Equipment designed to meet stringent regulatory requirements.',
    image: { src: '/images/industries/pharmaceutical.jpg', alt: 'Pharmaceutical Industry' },
    relevantProducts: ['fluid-bed-dryer', 'rapid-mixing-granulator', 'octagonal-blender', 'coating-pan', 'rotocone-vacuum-dryer'],
    applications: ['Tablet Manufacturing', 'Capsule Production', 'Granule Processing', 'Powder Blending'],
  },
  {
    id: 'nutraceutical',
    slug: 'nutraceutical',
    name: 'Nutraceutical',
    description: 'Equipment for dietary supplement and functional food manufacturing with gentle handling of active ingredients.',
    image: { src: '/images/industries/nutraceutical.jpg', alt: 'Nutraceutical Industry' },
    relevantProducts: ['fluid-bed-dryer', 'rapid-mixing-granulator', 'mass-mixer', 'coating-pan'],
    applications: ['Supplement Tablets', 'Protein Powders', 'Herbal Extracts', 'Functional Foods'],
  },
  {
    id: 'chemical',
    slug: 'chemical',
    name: 'Chemical',
    description: 'Corrosion-resistant equipment for specialty and fine chemical processing applications.',
    image: { src: '/images/industries/chemical.jpg', alt: 'Chemical Industry' },
    relevantProducts: ['rotocone-vacuum-dryer', 'filter-press', 'storage-vessel', 'mixing-vessel'],
    applications: ['Fine Chemicals', 'Specialty Compounds', 'Chemical Synthesis', 'Reaction Processing'],
  },
  {
    id: 'food-processing',
    slug: 'food-processing',
    name: 'Food Processing',
    description: 'Hygienic design machinery for food ingredient and additive production.',
    image: { src: '/images/industries/food-processing.jpg', alt: 'Food Processing Industry' },
    relevantProducts: ['fluid-bed-dryer', 'ribbon-blender', 'vibro-sifter', 'storage-vessel'],
    applications: ['Spice Processing', 'Flour Milling', 'Food Additives', 'Ingredient Blending'],
  },
  {
    id: 'cosmetics',
    slug: 'cosmetics',
    name: 'Cosmetics',
    description: 'Precision equipment for cosmetic and personal care product manufacturing.',
    image: { src: '/images/industries/cosmetics.jpg', alt: 'Cosmetics Industry' },
    relevantProducts: ['octacone-blender', 'mass-mixer', 'mixing-vessel', 'coating-pan'],
    applications: ['Cream Manufacturing', 'Powder Blending', 'Color Coating', 'Personal Care Products'],
  },
  {
    id: 'ayurvedic-herbal',
    slug: 'ayurvedic-herbal',
    name: 'Ayurvedic & Herbal',
    description: 'Traditional medicine processing equipment with gentle handling for natural products.',
    image: { src: '/images/industries/ayurvedic.jpg', alt: 'Ayurvedic and Herbal Industry' },
    relevantProducts: ['octagonal-blender', 'tray-dryer', 'vibro-sifter', 'mass-mixer'],
    applications: ['Herbal Powder Processing', 'Ayurvedic Tablets', 'Natural Extracts', 'Traditional Medicine'],
  },
  {
    id: 'rnd',
    slug: 'rnd',
    name: 'Research & Development',
    description: 'Lab and pilot-scale equipment for formulation development and process optimization.',
    image: { src: '/images/industries/rnd.jpg', alt: 'Research and Development' },
    relevantProducts: ['fluid-bed-dryer', 'rapid-mixing-granulator', 'octagonal-blender', 'coating-pan'],
    applications: ['Formulation Development', 'Process Optimization', 'Pilot Scale Production', 'Lab Research'],
  },
  {
    id: 'specialty-chemicals',
    slug: 'specialty-chemicals',
    name: 'Specialty Chemicals',
    description: 'Custom fabricated equipment for niche chemical applications requiring specialized materials.',
    image: { src: '/images/industries/specialty-chemicals.jpg', alt: 'Specialty Chemicals' },
    relevantProducts: ['rotocone-vacuum-dryer', 'filter-press', 'zero-hold-up-filter', 'manufacturing-vessel'],
    applications: ['Agrochemicals', 'Dyes & Pigments', 'Electronic Chemicals', 'Water Treatment Chemicals'],
  },
];

const specNA = 'Available as per customer requirement';
const specCustom = 'To be finalized based on process requirement';

export const products: Product[] = [
  {
    id: '1',
    slug: 'fluid-bed-dryer',
    name: 'Fluid Bed Dryer',
    category: 'Dryers',
    shortDescription: 'High-efficiency fluid bed dryer for uniform drying of granules, powders, and pellets in pharmaceutical and chemical industries.',
    description: 'The Fluid Bed Dryer (FBD) from Khushbu Pharma Machinery is designed for efficient and uniform drying of granules, powders, and other particulate materials. The system ensures optimal heat transfer and moisture removal through controlled fluidization. Available in multiple capacities and configurations to suit various process requirements in pharmaceutical, chemical, food, and nutraceutical industries.',
    applications: [
      'Drying of granules after wet granulation',
      'Drying of powders and pellets',
      'Pharmaceutical tablet manufacturing',
      'Chemical compound drying',
      'Nutraceutical processing',
    ],
    capacity: specNA,
    materialOfConstruction: 'SS 304 / SS 316 / SS 316L (as per requirement)',
    contactParts: 'SS 316 / SS 316L (as per product contact requirement)',
    nonContactParts: 'SS 304',
    power: specCustom,
    dimensions: specCustom,
    workingVolume: specNA,
    operatingTemperature: specCustom,
    operatingPressure: 'Atmospheric / Slight positive pressure',
    finish: 'Mirror polish / Matte finish (as required)',
    motor: specCustom,
    gearbox: specCustom,
    controls: 'PLC based / Manual control panel (as per configuration)',
    features: [
      'Uniform drying through fluidization',
      'Adjustable air flow and temperature',
      'Easy cleaning and maintenance',
      'GMP compliant design',
      'Available in multiple batch sizes',
      'SS 316 contact parts',
      'Efficient filtration system',
    ],
    industries: ['Pharmaceutical', 'Chemical', 'Nutraceutical', 'Food Processing'],
    images: [
      { src: '/images/products/fluid-bed-dryer.jpg', alt: 'Fluid Bed Dryer - Pharmaceutical Equipment' },
      { src: '/images/products/fluid-bed-dryer-side.jpg', alt: 'Fluid Bed Dryer Side View' },
    ],
    technicalSpecifications: [
      { parameter: 'Machine Type', specification: 'Fluid Bed Dryer (FBD)' },
      { parameter: 'Capacity', specification: specNA },
      { parameter: 'Material of Construction', specification: 'SS 304 / SS 316 / SS 316L' },
      { parameter: 'Contact Parts', specification: 'SS 316 / SS 316L' },
      { parameter: 'Surface Finish', specification: 'Mirror polish / Matte finish' },
      { parameter: 'Control System', specification: 'PLC based / Manual' },
      { parameter: 'Power Requirement', specification: specCustom },
      { parameter: 'Air Handling Unit', specification: 'As per capacity' },
      { parameter: 'Filtration', specification: 'Bag filter / HEPA filter' },
    ],
    faq: [
      {
        question: 'What is a Fluid Bed Dryer used for?',
        answer: 'A Fluid Bed Dryer is used for drying granules, powders, and pellets by suspending them in a stream of heated air. It is commonly used in pharmaceutical, chemical, and food processing industries for uniform and efficient drying.',
      },
      {
        question: 'What materials are available for the Fluid Bed Dryer?',
        answer: 'The Fluid Bed Dryer is available in SS 304, SS 316, and SS 316L. Contact parts can be specified as SS 316 or SS 316L based on product compatibility and regulatory requirements.',
      },
      {
        question: 'Can the Fluid Bed Dryer be customized?',
        answer: 'Yes, all equipment from Khushbu Pharma Machinery can be customized according to specific process requirements, capacity needs, and installation constraints.',
      },
    ],
    seoTitle: 'Fluid Bed Dryer Manufacturer | Pharmaceutical FBD | Khushbu Pharma Machinery',
    seoDescription: 'Khushbu Pharma Machinery manufactures high-efficiency Fluid Bed Dryers (FBD) for pharmaceutical, chemical, and food industries. Available in multiple capacities with SS 304/316 construction.',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '2',
    slug: 'rapid-mixing-granulator',
    name: 'Rapid Mixing Granulator',
    category: 'Granulators',
    shortDescription: 'High-shear rapid mixing granulator for wet granulation in pharmaceutical tablet manufacturing.',
    description: 'The Rapid Mixing Granulator (RMG) from Khushbu Pharma Machinery is designed for high-shear wet granulation. It ensures uniform mixing of powders followed by efficient granulation through the addition of binder solution. The equipment is engineered for consistent granule quality and optimized process times.',
    applications: [
      'Wet granulation for tablet manufacturing',
      'Mixing and granulating pharmaceutical powders',
      'Chemical compound granulation',
      'Nutraceutical granule production',
    ],
    capacity: specNA,
    materialOfConstruction: 'SS 304 / SS 316 / SS 316L',
    contactParts: 'SS 316 / SS 316L',
    nonContactParts: 'SS 304',
    power: specCustom,
    dimensions: specCustom,
    workingVolume: specNA,
    operatingTemperature: 'Ambient to process temperature',
    operatingPressure: 'Atmospheric',
    finish: 'Mirror polish (contact parts)',
    motor: specCustom,
    gearbox: specCustom,
    controls: 'PLC based / Manual panel',
    features: [
      'High-shear mixing and granulation',
      'Uniform granule size distribution',
      'Adjustable impeller and chopper speed',
      'Easy bowl lifting/lowering mechanism',
      'GMP compliant construction',
      'Easy to clean and maintain',
      'SS 316L contact parts',
    ],
    industries: ['Pharmaceutical', 'Nutraceutical', 'Chemical', 'Ayurvedic & Herbal'],
    images: [
      { src: '/images/products/rmg.jpg', alt: 'Rapid Mixing Granulator' },
    ],
    technicalSpecifications: [
      { parameter: 'Machine Type', specification: 'Rapid Mixing Granulator (RMG)' },
      { parameter: 'Capacity', specification: specNA },
      { parameter: 'Material of Construction', specification: 'SS 304 / SS 316 / SS 316L' },
      { parameter: 'Contact Parts', specification: 'SS 316 / SS 316L' },
      { parameter: 'Impeller Type', specification: 'Three-blade / Multi-blade' },
      { parameter: 'Chopper', specification: 'High-speed chopper' },
      { parameter: 'Surface Finish', specification: 'Mirror polish' },
      { parameter: 'Control System', specification: 'PLC based / Manual' },
    ],
    faq: [
      {
        question: 'What is a Rapid Mixing Granulator?',
        answer: 'A Rapid Mixing Granulator (RMG) is a high-shear mixer used for wet granulation in pharmaceutical manufacturing. It combines powder mixing and granulation in a single unit operation.',
      },
      {
        question: 'What capacities are available?',
        answer: 'The RMG is available in various capacities to suit different batch sizes. Contact our team for specific capacity options and recommendations for your process.',
      },
    ],
    seoTitle: 'Rapid Mixing Granulator Manufacturer | RMG | Khushbu Pharma Machinery',
    seoDescription: 'Khushbu Pharma Machinery manufactures Rapid Mixing Granulators (RMG) for pharmaceutical wet granulation. High-shear mixing with SS 316 contact parts.',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '3',
    slug: 'octagonal-blender',
    name: 'Octagonal Blender',
    category: 'Blenders',
    shortDescription: 'Octagonal blender for gentle and homogeneous blending of powders and granules.',
    description: 'The Octagonal Blender from Khushbu Pharma Machinery features a unique octagonal shape that provides excellent blending efficiency with minimal shear. The geometry ensures uniform mixing of powders and granules while maintaining product integrity. Ideal for pharmaceutical, food, and chemical applications.',
    applications: [
      'Blending of pharmaceutical powders',
      'Mixing of granules and pellets',
      'Food ingredient blending',
      'Chemical powder mixing',
      'Nutraceutical blending',
    ],
    capacity: specNA,
    materialOfConstruction: 'SS 304 / SS 316 / SS 316L',
    contactParts: 'SS 316 / SS 316L',
    nonContactParts: 'SS 304',
    power: specCustom,
    dimensions: specCustom,
    workingVolume: specNA,
    operatingTemperature: 'Ambient',
    operatingPressure: 'Atmospheric',
    finish: 'Mirror polish / Sanitary finish',
    motor: specCustom,
    gearbox: specCustom,
    controls: 'Variable frequency drive (VFD)',
    features: [
      'Unique octagonal geometry for superior blending',
      'Low shear mixing',
      'Easy to clean and maintain',
      'GMP compliant design',
      'Variable speed control',
      'SS 316 contact parts',
      'Safety interlocks',
    ],
    industries: ['Pharmaceutical', 'Food Processing', 'Nutraceutical', 'Ayurvedic & Herbal'],
    images: [
      { src: '/images/products/octagonal-blender.jpg', alt: 'Octagonal Blender' },
    ],
    technicalSpecifications: [
      { parameter: 'Machine Type', specification: 'Octagonal Blender' },
      { parameter: 'Capacity', specification: specNA },
      { parameter: 'Material of Construction', specification: 'SS 304 / SS 316 / SS 316L' },
      { parameter: 'Contact Parts', specification: 'SS 316 / SS 316L' },
      { parameter: 'Geometry', specification: 'Octagonal' },
      { parameter: 'Speed Control', specification: 'VFD' },
      { parameter: 'Surface Finish', specification: 'Mirror polish / Sanitary' },
    ],
    faq: [
      {
        question: 'Why choose an octagonal blender over a V-blender?',
        answer: 'The octagonal blender provides more uniform blending with less dead space compared to some traditional blender geometries. Its shape promotes better material movement and mixing efficiency.',
      },
    ],
    seoTitle: 'Octagonal Blender Manufacturer | Pharmaceutical Blender | Khushbu Pharma Machinery',
    seoDescription: 'Khushbu Pharma Machinery manufactures Octagonal Blenders for pharmaceutical, food, and chemical industries. GMP compliant design with SS 316 contact parts.',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '4',
    slug: 'octacone-blender',
    name: 'Octacone Blender',
    category: 'Blenders',
    shortDescription: 'Octacone blender combining octagonal and conical geometry for efficient powder blending.',
    description: 'The Octacone Blender features a unique design combining octagonal and conical geometry for efficient blending of powders and granules. The hybrid shape ensures excellent material flow and uniform mixing.',
    applications: [
      'Pharmaceutical powder blending',
      'Cosmetic ingredient mixing',
      'Chemical compound blending',
    ],
    capacity: specNA,
    materialOfConstruction: 'SS 304 / SS 316 / SS 316L',
    contactParts: 'SS 316 / SS 316L',
    nonContactParts: 'SS 304',
    power: specCustom,
    dimensions: specCustom,
    workingVolume: specNA,
    operatingTemperature: 'Ambient',
    operatingPressure: 'Atmospheric',
    finish: 'Mirror polish',
    motor: specCustom,
    gearbox: specCustom,
    controls: 'VFD based speed control',
    features: [
      'Hybrid octagonal-conical geometry',
      'Excellent material flow',
      'Easy discharge',
      'GMP compliant design',
      'Low shear blending',
    ],
    industries: ['Pharmaceutical', 'Cosmetics', 'Chemical'],
    images: [
      { src: '/images/products/octacone-blender.jpg', alt: 'Octacone Blender' },
    ],
    technicalSpecifications: [
      { parameter: 'Machine Type', specification: 'Octacone Blender' },
      { parameter: 'Capacity', specification: specNA },
      { parameter: 'Material of Construction', specification: 'SS 304 / SS 316 / SS 316L' },
      { parameter: 'Contact Parts', specification: 'SS 316 / SS 316L' },
      { parameter: 'Surface Finish', specification: 'Mirror polish' },
      { parameter: 'Speed Control', specification: 'VFD' },
    ],
    faq: [],
    seoTitle: 'Octacone Blender Manufacturer | Khushbu Pharma Machinery',
    seoDescription: 'Khushbu Pharma Machinery manufactures Octacone Blenders with hybrid octagonal-conical geometry for efficient powder blending.',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '5',
    slug: 'double-cone-blender',
    name: 'Double Cone Blender',
    category: 'Blenders',
    shortDescription: 'Double cone blender for gentle blending of powders, granules, and tablets.',
    description: 'The Double Cone Blender is designed for gentle and efficient blending of dry powders, granules, and even coated tablets. The double cone shape ensures consistent mixing with minimal product degradation.',
    applications: [
      'Blending of dry powders',
      'Mixing of granules',
      'Gentle handling of coated tablets',
      'Pharmaceutical powder blending',
    ],
    capacity: specNA,
    materialOfConstruction: 'SS 304 / SS 316 / SS 316L',
    contactParts: 'SS 316 / SS 316L',
    nonContactParts: 'SS 304',
    power: specCustom,
    dimensions: specCustom,
    workingVolume: specNA,
    operatingTemperature: 'Ambient',
    operatingPressure: 'Atmospheric',
    finish: 'Mirror polish',
    motor: specCustom,
    gearbox: specCustom,
    controls: 'VFD',
    features: [
      'Gentle blending action',
      'Double cone geometry',
      'Easy loading and discharging',
      'GMP compliant',
      'Variable speed',
    ],
    industries: ['Pharmaceutical', 'Food Processing', 'Nutraceutical'],
    images: [
      { src: '/images/products/double-cone-blender.jpg', alt: 'Double Cone Blender' },
    ],
    technicalSpecifications: [
      { parameter: 'Machine Type', specification: 'Double Cone Blender' },
      { parameter: 'Capacity', specification: specNA },
      { parameter: 'Material of Construction', specification: 'SS 304 / SS 316 / SS 316L' },
      { parameter: 'Contact Parts', specification: 'SS 316 / SS 316L' },
      { parameter: 'Surface Finish', specification: 'Mirror polish' },
      { parameter: 'Speed Control', specification: 'VFD' },
    ],
    faq: [],
    seoTitle: 'Double Cone Blender Manufacturer | Khushbu Pharma Machinery',
    seoDescription: 'Khushbu Pharma Machinery manufactures Double Cone Blenders for gentle and efficient blending of pharmaceutical powders and granules.',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '6',
    slug: 'mass-mixer',
    name: 'Mass Mixer',
    category: 'Mixers & Mills',
    shortDescription: 'High-shear mass mixer for mixing viscous masses and wet granulation.',
    description: 'The Mass Mixer from Khushbu Pharma Machinery is designed for high-shear mixing of viscous masses, wet granulation, and mixing of thick pastes. The equipment handles materials that require intensive mixing action.',
    applications: [
      'Mixing of viscous masses',
      'Wet granulation',
      'Mixing of thick pastes',
      'Pharmaceutical mass mixing',
      'Cosmetic cream preparation',
    ],
    capacity: specNA,
    materialOfConstruction: 'SS 304 / SS 316 / SS 316L',
    contactParts: 'SS 316 / SS 316L',
    nonContactParts: 'SS 304',
    power: specCustom,
    dimensions: specCustom,
    workingVolume: specNA,
    operatingTemperature: 'Ambient to process temperature',
    operatingPressure: 'Atmospheric',
    finish: 'Mirror polish',
    motor: specCustom,
    gearbox: specCustom,
    controls: 'Manual / PLC based',
    features: [
      'High-shear mixing action',
      'Suitable for viscous materials',
      'Tilting mechanism for discharge',
      'GMP compliant design',
      'Stainless steel construction',
    ],
    industries: ['Pharmaceutical', 'Cosmetics', 'Ayurvedic & Herbal', 'Chemical'],
    images: [
      { src: '/images/products/mass-mixer.jpg', alt: 'Mass Mixer' },
    ],
    technicalSpecifications: [
      { parameter: 'Machine Type', specification: 'Mass Mixer' },
      { parameter: 'Capacity', specification: specNA },
      { parameter: 'Material of Construction', specification: 'SS 304 / SS 316 / SS 316L' },
      { parameter: 'Contact Parts', specification: 'SS 316 / SS 316L' },
      { parameter: 'Mixing Action', specification: 'High-shear' },
      { parameter: 'Discharge', specification: 'Tilting mechanism' },
    ],
    faq: [],
    seoTitle: 'Mass Mixer Manufacturer | Pharmaceutical Mass Mixer | Khushbu Pharma Machinery',
    seoDescription: 'Khushbu Pharma Machinery manufactures Mass Mixers for high-shear mixing of viscous masses and wet granulation in pharmaceutical and cosmetic industries.',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '7',
    slug: 'ribbon-blender',
    name: 'Ribbon Blender',
    category: 'Blenders',
    shortDescription: 'Ribbon blender for efficient blending of dry powders, granules, and pastes.',
    description: 'The Ribbon Blender features a double helical ribbon agitator that provides efficient mixing of dry powders, granules, and even pastes. The design ensures uniform mixing with good radial and axial movement.',
    applications: [
      'Blending of dry powders',
      'Mixing of granules',
      'Food ingredient blending',
      'Chemical mixing',
      'Paste mixing',
    ],
    capacity: specNA,
    materialOfConstruction: 'SS 304 / SS 316 / SS 316L',
    contactParts: 'SS 316 / SS 316L',
    nonContactParts: 'SS 304',
    power: specCustom,
    dimensions: specCustom,
    workingVolume: specNA,
    operatingTemperature: 'Ambient',
    operatingPressure: 'Atmospheric',
    finish: 'Mirror polish / Mill finish',
    motor: specCustom,
    gearbox: specCustom,
    controls: 'VFD based',
    features: [
      'Double helical ribbon agitator',
      'Efficient radial and axial mixing',
      'Suitable for powders and pastes',
      'GMP compliant',
      'Variable speed control',
      'Bottom discharge with butterfly valve',
    ],
    industries: ['Pharmaceutical', 'Food Processing', 'Chemical', 'Specialty Chemicals'],
    images: [
      { src: '/images/products/ribbon-blender.jpg', alt: 'Ribbon Blender' },
    ],
    technicalSpecifications: [
      { parameter: 'Machine Type', specification: 'Ribbon Blender' },
      { parameter: 'Capacity', specification: specNA },
      { parameter: 'Material of Construction', specification: 'SS 304 / SS 316 / SS 316L' },
      { parameter: 'Contact Parts', specification: 'SS 316 / SS 316L' },
      { parameter: 'Agitator Type', specification: 'Double helical ribbon' },
      { parameter: 'Discharge', specification: 'Bottom butterfly valve' },
    ],
    faq: [],
    seoTitle: 'Ribbon Blender Manufacturer | Pharmaceutical Ribbon Blender | Khushbu Pharma Machinery',
    seoDescription: 'Khushbu Pharma Machinery manufactures Ribbon Blenders with double helical ribbon agitator for efficient blending in pharmaceutical, food, and chemical industries.',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '8',
    slug: 'rotocone-vacuum-dryer',
    name: 'Rotocone Vacuum Dryer',
    category: 'Dryers',
    shortDescription: 'Rotocone vacuum dryer for efficient drying under vacuum with gentle handling.',
    description: 'The Rotocone Vacuum Dryer (RCVD) provides efficient drying under vacuum conditions. The conical shape with internal screw ensures gentle handling of materials while providing excellent heat transfer and moisture removal.',
    applications: [
      'Drying of heat-sensitive materials',
      'Drying under vacuum',
      'Pharmaceutical drying',
      'Chemical compound drying',
      'Solvent recovery',
    ],
    capacity: specNA,
    materialOfConstruction: 'SS 304 / SS 316 / SS 316L',
    contactParts: 'SS 316 / SS 316L',
    nonContactParts: 'SS 304',
    power: specCustom,
    dimensions: specCustom,
    workingVolume: specNA,
    operatingTemperature: 'Up to 200°C (as per design)',
    operatingPressure: 'Vacuum (as per design)',
    finish: 'Mirror polish',
    motor: specCustom,
    gearbox: specCustom,
    controls: 'PLC / Manual panel',
    features: [
      'Vacuum drying capability',
      'Gentle material handling',
      'Internal screw for material movement',
      'Conical shape for complete discharge',
      'Jacketed for heating',
      'GMP compliant',
    ],
    industries: ['Pharmaceutical', 'Chemical', 'Specialty Chemicals', 'Nutraceutical'],
    images: [
      { src: '/images/products/rotocone-vacuum-dryer.jpg', alt: 'Rotocone Vacuum Dryer' },
    ],
    technicalSpecifications: [
      { parameter: 'Machine Type', specification: 'Rotocone Vacuum Dryer (RCVD)' },
      { parameter: 'Capacity', specification: specNA },
      { parameter: 'Material of Construction', specification: 'SS 304 / SS 316 / SS 316L' },
      { parameter: 'Contact Parts', specification: 'SS 316 / SS 316L' },
      { parameter: 'Operating Pressure', specification: 'Vacuum' },
      { parameter: 'Heating', specification: 'Jacketed (steam/hot water/oil)' },
      { parameter: 'Internal Agitator', specification: 'Screw type' },
    ],
    faq: [
      {
        question: 'What is a Rotocone Vacuum Dryer?',
        answer: 'A Rotocone Vacuum Dryer (RCVD) is a conical dryer that operates under vacuum conditions for efficient drying of heat-sensitive materials. The internal screw ensures gentle mixing and uniform drying.',
      },
    ],
    seoTitle: 'Rotocone Vacuum Dryer Manufacturer | RCVD | Khushbu Pharma Machinery',
    seoDescription: 'Khushbu Pharma Machinery manufactures Rotocone Vacuum Dryers (RCVD) for efficient vacuum drying in pharmaceutical and chemical industries.',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '9',
    slug: 'tray-dryer',
    name: 'Tray Dryer',
    category: 'Dryers',
    shortDescription: 'Industrial tray dryer for batch drying of powders, granules, and wet materials.',
    description: 'The Tray Dryer from Khushbu Pharma Machinery is a convection-type batch dryer suitable for drying powders, granules, wet cakes, and other materials. Multiple trays ensure even drying through forced air circulation.',
    applications: [
      'Drying of powders and granules',
      'Drying of wet cakes',
      'Herbal and ayurvedic product drying',
      'Pharmaceutical batch drying',
    ],
    capacity: specNA,
    materialOfConstruction: 'SS 304 / SS 316 / Aluminum',
    contactParts: 'SS 304 / SS 316 / SS Trays',
    nonContactParts: 'SS 304 / GI',
    power: specCustom,
    dimensions: specCustom,
    workingVolume: specNA,
    operatingTemperature: 'Up to 120°C',
    operatingPressure: 'Atmospheric',
    finish: 'Standard / SS finish',
    motor: specCustom,
    gearbox: 'N/A',
    controls: 'Temperature controller / Timer',
    features: [
      'Multiple tray capacity',
      'Forced air circulation',
      'Temperature control',
      'Easy tray loading/unloading',
      'Economical batch drying',
    ],
    industries: ['Pharmaceutical', 'Ayurvedic & Herbal', 'Food Processing', 'Chemical'],
    images: [
      { src: '/images/products/tray-dryer.jpg', alt: 'Tray Dryer' },
    ],
    technicalSpecifications: [
      { parameter: 'Machine Type', specification: 'Tray Dryer' },
      { parameter: 'Capacity', specification: specNA },
      { parameter: 'Material of Construction', specification: 'SS 304 / SS 316 / Aluminum' },
      { parameter: 'Trays', specification: 'SS / Aluminum (removable)' },
      { parameter: 'Heating', specification: 'Electric / Steam' },
      { parameter: 'Air Circulation', specification: 'Forced convection' },
    ],
    faq: [],
    seoTitle: 'Tray Dryer Manufacturer | Industrial Tray Dryer | Khushbu Pharma Machinery',
    seoDescription: 'Khushbu Pharma Machinery manufactures Tray Dryers for batch drying of powders, granules, and wet materials in pharmaceutical and chemical industries.',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '10',
    slug: 'vacuum-tray-dryer',
    name: 'Vacuum Tray Dryer',
    category: 'Dryers',
    shortDescription: 'Vacuum tray dryer for low-temperature drying of heat-sensitive materials.',
    description: 'The Vacuum Tray Dryer operates under reduced pressure for efficient drying of heat-sensitive and oxidation-prone materials at lower temperatures.',
    applications: [
      'Drying of heat-sensitive materials',
      'Drying under vacuum',
      'Pharmaceutical vacuum drying',
      'Oxidation-prone material drying',
    ],
    capacity: specNA,
    materialOfConstruction: 'SS 304 / SS 316',
    contactParts: 'SS 316',
    nonContactParts: 'SS 304',
    power: specCustom,
    dimensions: specCustom,
    workingVolume: specNA,
    operatingTemperature: 'Up to 80°C under vacuum',
    operatingPressure: 'Vacuum',
    finish: 'Mirror polish',
    motor: specCustom,
    gearbox: 'N/A',
    controls: 'Temperature and vacuum controllers',
    features: [
      'Low-temperature drying',
      'Vacuum operation',
      'Prevents oxidation',
      'Uniform drying',
      'Jacketed chamber',
    ],
    industries: ['Pharmaceutical', 'Chemical', 'Specialty Chemicals'],
    images: [
      { src: '/images/products/vacuum-tray-dryer.jpg', alt: 'Vacuum Tray Dryer' },
    ],
    technicalSpecifications: [
      { parameter: 'Machine Type', specification: 'Vacuum Tray Dryer' },
      { parameter: 'Capacity', specification: specNA },
      { parameter: 'Material of Construction', specification: 'SS 304 / SS 316' },
      { parameter: 'Operating Pressure', specification: 'Vacuum' },
      { parameter: 'Heating', specification: 'Jacketed (steam/hot water)' },
      { parameter: 'Trays', specification: 'SS 316 (removable)' },
    ],
    faq: [],
    seoTitle: 'Vacuum Tray Dryer Manufacturer | Khushbu Pharma Machinery',
    seoDescription: 'Khushbu Pharma Machinery manufactures Vacuum Tray Dryers for low-temperature drying of heat-sensitive pharmaceutical and chemical materials.',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '11',
    slug: 'multi-mill',
    name: 'Multi Mill',
    category: 'Mixers & Mills',
    shortDescription: 'Multi mill for size reduction, grinding, and mixing in a single operation.',
    description: 'The Multi Mill from Khushbu Pharma Machinery is a versatile machine that performs multiple operations including grinding, mixing, and size reduction. Suitable for pharmaceutical, chemical, and food applications.',
    applications: [
      'Grinding of herbs and spices',
      'Size reduction of pharmaceutical materials',
      'Mixing and grinding',
      'Pulverizing operations',
    ],
    capacity: specNA,
    materialOfConstruction: 'SS 304 / SS 316',
    contactParts: 'SS 316',
    nonContactParts: 'SS 304',
    power: specCustom,
    dimensions: specCustom,
    workingVolume: specNA,
    operatingTemperature: 'Ambient',
    operatingPressure: 'Atmospheric',
    finish: 'Standard / SS finish',
    motor: specCustom,
    gearbox: 'N/A',
    controls: 'ON/OFF with overload protection',
    features: [
      'Multi-purpose operation',
      'Various screen sizes',
      'Easy screen change',
      'Stainless steel construction',
      'Dust collection provision',
    ],
    industries: ['Pharmaceutical', 'Ayurvedic & Herbal', 'Food Processing', 'Chemical'],
    images: [
      { src: '/images/products/multi-mill.jpg', alt: 'Multi Mill' },
    ],
    technicalSpecifications: [
      { parameter: 'Machine Type', specification: 'Multi Mill' },
      { parameter: 'Capacity', specification: specNA },
      { parameter: 'Material of Construction', specification: 'SS 304 / SS 316' },
      { parameter: 'Screens', specification: 'Various mesh sizes available' },
      { parameter: 'Output', specification: 'Adjustable via screen selection' },
    ],
    faq: [],
    seoTitle: 'Multi Mill Manufacturer | Pharmaceutical Multi Mill | Khushbu Pharma Machinery',
    seoDescription: 'Khushbu Pharma Machinery manufactures Multi Mills for grinding, mixing, and size reduction in pharmaceutical, food, and chemical industries.',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '12',
    slug: 'coating-pan',
    name: 'Coating Pan',
    category: 'Coating Equipment',
    shortDescription: 'Pharmaceutical coating pan for film, sugar, and enteric coating of tablets.',
    description: 'The Coating Pan from Khushbu Pharma Machinery is designed for uniform coating of tablets, pellets, and other solid dosage forms. Available in various sizes for pilot to production scale.',
    applications: [
      'Film coating of tablets',
      'Sugar coating of tablets',
      'Enteric coating',
      'Pellet coating',
      'Color coating',
    ],
    capacity: specNA,
    materialOfConstruction: 'SS 304 / SS 316',
    contactParts: 'SS 316',
    nonContactParts: 'SS 304',
    power: specCustom,
    dimensions: specCustom,
    workingVolume: specNA,
    operatingTemperature: 'Ambient to 80°C',
    operatingPressure: 'Atmospheric',
    finish: 'Mirror polish (pan interior)',
    motor: specCustom,
    gearbox: specCustom,
    controls: 'Variable speed for pan rotation',
    features: [
      'Uniform coating',
      'Adjustable pan speed',
      'Spray gun provision',
      'Heating option',
      'Various pan sizes',
      'GMP compliant',
    ],
    industries: ['Pharmaceutical', 'Nutraceutical', 'Ayurvedic & Herbal'],
    images: [
      { src: '/images/products/coating-pan.jpg', alt: 'Coating Pan' },
    ],
    technicalSpecifications: [
      { parameter: 'Machine Type', specification: 'Coating Pan' },
      { parameter: 'Capacity', specification: specNA },
      { parameter: 'Material of Construction', specification: 'SS 304 / SS 316' },
      { parameter: 'Pan Speed', specification: 'Variable (VFD)' },
      { parameter: 'Heating', specification: 'Optional (electric/hot air)' },
      { parameter: 'Coating Type', specification: 'Film / Sugar / Enteric' },
    ],
    faq: [],
    seoTitle: 'Coating Pan Manufacturer | Pharmaceutical Coating Pan | Khushbu Pharma Machinery',
    seoDescription: 'Khushbu Pharma Machinery manufactures Coating Pans for film, sugar, and enteric coating of pharmaceutical tablets.',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '13',
    slug: 'storage-vessel',
    name: 'Storage Vessel',
    category: 'Process Vessels',
    shortDescription: 'Custom fabricated storage vessels for pharmaceutical and chemical applications.',
    description: 'Storage Vessels from Khushbu Pharma Machinery are custom fabricated to customer specifications for storing raw materials, intermediates, and finished products.',
    applications: [
      'Storage of raw materials',
      'Storage of intermediates',
      'Storage of finished products',
      'Liquid storage',
    ],
    capacity: specNA,
    materialOfConstruction: 'SS 304 / SS 316 / SS 316L',
    contactParts: 'SS 316 / SS 316L',
    nonContactParts: 'SS 304',
    power: 'N/A',
    dimensions: 'Custom fabricated',
    workingVolume: specNA,
    operatingTemperature: 'As per requirement',
    operatingPressure: 'Atmospheric / Pressurized (as per design)',
    finish: 'Mirror polish / Matte finish',
    motor: 'N/A',
    gearbox: 'N/A',
    controls: 'Level indicators / Sensors (as required)',
    features: [
      'Custom fabrication',
      'Various capacities',
      'SS 304/316 construction',
      'With/without agitation',
      'Manhole and nozzles as required',
      'GMP design',
    ],
    industries: ['Pharmaceutical', 'Chemical', 'Food Processing', 'Specialty Chemicals'],
    images: [
      { src: '/images/products/storage-vessel.jpg', alt: 'Storage Vessel' },
    ],
    technicalSpecifications: [
      { parameter: 'Machine Type', specification: 'Storage Vessel' },
      { parameter: 'Capacity', specification: 'Custom fabricated' },
      { parameter: 'Material of Construction', specification: 'SS 304 / SS 316 / SS 316L' },
      { parameter: 'Design', specification: 'Vertical / Horizontal' },
      { parameter: 'Pressure Rating', specification: 'As per requirement' },
      { parameter: 'Agitation', specification: 'Optional' },
    ],
    faq: [],
    seoTitle: 'Storage Vessel Manufacturer | SS Storage Vessel | Khushbu Pharma Machinery',
    seoDescription: 'Khushbu Pharma Machinery manufactures custom Storage Vessels in SS 304/316 for pharmaceutical and chemical applications.',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '14',
    slug: 'manufacturing-vessel',
    name: 'Manufacturing Vessel',
    category: 'Process Vessels',
    shortDescription: 'Manufacturing vessels for pharmaceutical and chemical process applications.',
    description: 'Manufacturing Vessels from Khushbu Pharma Machinery are designed and fabricated for specific process requirements including reaction, mixing, and processing operations.',
    applications: [
      'Chemical reaction vessels',
      'Pharmaceutical processing',
      'Mixing and blending vessels',
      'Heating and cooling operations',
    ],
    capacity: specNA,
    materialOfConstruction: 'SS 304 / SS 316 / SS 316L',
    contactParts: 'SS 316 / SS 316L',
    nonContactParts: 'SS 304',
    power: specCustom,
    dimensions: 'Custom fabricated',
    workingVolume: specNA,
    operatingTemperature: 'As per requirement',
    operatingPressure: 'Atmospheric / Pressurized (as per design)',
    finish: 'Mirror polish',
    motor: specCustom,
    gearbox: specCustom,
    controls: 'Temperature, pressure, level controls (as required)',
    features: [
      'Custom process design',
      'Jacketed for heating/cooling',
      'Agitator options',
      'Various nozzle configurations',
      'Pressure rated options',
      'GMP compliant',
    ],
    industries: ['Pharmaceutical', 'Chemical', 'Specialty Chemicals'],
    images: [
      { src: '/images/products/manufacturing-vessel.jpg', alt: 'Manufacturing Vessel' },
    ],
    technicalSpecifications: [
      { parameter: 'Machine Type', specification: 'Manufacturing Vessel' },
      { parameter: 'Capacity', specification: 'Custom fabricated' },
      { parameter: 'Material of Construction', specification: 'SS 304 / SS 316 / SS 316L' },
      { parameter: 'Heating/Cooling', specification: 'Jacketed (Dimple / Limpet)' },
      { parameter: 'Agitation', specification: 'Anchor / Propeller / Turbine' },
      { parameter: 'Pressure Rating', specification: 'As per ASME / IS standards' },
    ],
    faq: [],
    seoTitle: 'Manufacturing Vessel Manufacturer | Process Vessel | Khushbu Pharma Machinery',
    seoDescription: 'Khushbu Pharma Machinery manufactures custom Manufacturing Vessels for pharmaceutical and chemical process applications.',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '15',
    slug: 'mixing-vessel',
    name: 'Mixing Vessel',
    category: 'Process Vessels',
    shortDescription: 'Mixing vessels with agitation for pharmaceutical and chemical applications.',
    description: 'Mixing Vessels from Khushbu Pharma Machinery are equipped with appropriate agitation systems for mixing, blending, and processing liquids, slurries, and semi-solid materials.',
    applications: [
      'Liquid mixing',
      'Slurry preparation',
      'Solution preparation',
      'Pharmaceutical liquid processing',
    ],
    capacity: specNA,
    materialOfConstruction: 'SS 304 / SS 316 / SS 316L',
    contactParts: 'SS 316 / SS 316L',
    nonContactParts: 'SS 304',
    power: specCustom,
    dimensions: 'Custom fabricated',
    workingVolume: specNA,
    operatingTemperature: 'As per requirement',
    operatingPressure: 'Atmospheric / Pressurized',
    finish: 'Mirror polish',
    motor: specCustom,
    gearbox: specCustom,
    controls: 'Speed control, temperature monitoring',
    features: [
      'Various agitator types',
      'Variable speed',
      'Jacketed option',
      'Baffles for efficient mixing',
      'Multiple nozzle connections',
    ],
    industries: ['Pharmaceutical', 'Chemical', 'Food Processing', 'Cosmetics'],
    images: [
      { src: '/images/products/mixing-vessel.jpg', alt: 'Mixing Vessel' },
    ],
    technicalSpecifications: [
      { parameter: 'Machine Type', specification: 'Mixing Vessel' },
      { parameter: 'Capacity', specification: 'Custom fabricated' },
      { parameter: 'Material of Construction', specification: 'SS 304 / SS 316 / SS 316L' },
      { parameter: 'Agitator Type', specification: 'Anchor / Propeller / Turbine / Ribbon' },
      { parameter: 'Speed Control', specification: 'VFD' },
      { parameter: 'Heating/Cooling', specification: 'Optional jacketed' },
    ],
    faq: [],
    seoTitle: 'Mixing Vessel Manufacturer | SS Mixing Vessel | Khushbu Pharma Machinery',
    seoDescription: 'Khushbu Pharma Machinery manufactures Mixing Vessels with various agitation systems for pharmaceutical and chemical applications.',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '16',
    slug: 'zero-hold-up-filter',
    name: 'Zero Hold Up Filter',
    category: 'Filtration & Sifting',
    shortDescription: 'Zero hold up filter for complete filtration with no product retention.',
    description: 'The Zero Hold Up Filter from Khushbu Pharma Machinery ensures complete filtration with minimal product retention in the filter housing. Ideal for valuable product filtration.',
    applications: [
      'Filtration of pharmaceutical liquids',
      'Clarification of solutions',
      'Product filtration with zero loss',
      'Chemical filtration',
    ],
    capacity: specNA,
    materialOfConstruction: 'SS 304 / SS 316 / SS 316L',
    contactParts: 'SS 316 / SS 316L',
    nonContactParts: 'SS 304',
    power: 'N/A (gravity/pressure fed)',
    dimensions: specCustom,
    workingVolume: specNA,
    operatingTemperature: 'As per requirement',
    operatingPressure: 'Atmospheric / Low pressure',
    finish: 'Mirror polish',
    motor: 'N/A',
    gearbox: 'N/A',
    controls: 'Manual operation',
    features: [
      'Zero product retention',
      'Easy filter media change',
      'SS 316 contact parts',
      'Various filter media options',
      'GMP design',
    ],
    industries: ['Pharmaceutical', 'Chemical', 'Food Processing'],
    images: [
      { src: '/images/products/zero-hold-up-filter.jpg', alt: 'Zero Hold Up Filter' },
    ],
    technicalSpecifications: [
      { parameter: 'Machine Type', specification: 'Zero Hold Up Filter' },
      { parameter: 'Capacity', specification: specNA },
      { parameter: 'Material of Construction', specification: 'SS 304 / SS 316 / SS 316L' },
      { parameter: 'Filter Media', specification: 'Filter cloth / Mesh / Membrane' },
      { parameter: 'Product Retention', specification: 'Zero hold up' },
    ],
    faq: [],
    seoTitle: 'Zero Hold Up Filter Manufacturer | Pharmaceutical Filter | Khushbu Pharma Machinery',
    seoDescription: 'Khushbu Pharma Machinery manufactures Zero Hold Up Filters for complete filtration with minimal product retention in pharmaceutical and chemical industries.',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '17',
    slug: 'filter-press',
    name: 'Filter Press',
    category: 'Filtration & Sifting',
    shortDescription: 'Filter press for solid-liquid separation in pharmaceutical and chemical industries.',
    description: 'The Filter Press from Khushbu Pharma Machinery is designed for efficient solid-liquid separation. Available in various plate sizes and configurations for different batch sizes.',
    applications: [
      'Solid-liquid separation',
      'Pharmaceutical filtration',
      'Chemical slurry filtration',
      'Mother liquor separation',
      'Waste water treatment',
    ],
    capacity: specNA,
    materialOfConstruction: 'SS 304 / SS 316 / PP',
    contactParts: 'SS 316 / PP',
    nonContactParts: 'SS 304 / MS',
    power: specCustom,
    dimensions: specCustom,
    workingVolume: specNA,
    operatingTemperature: 'As per requirement',
    operatingPressure: 'Up to 10-15 kg/cm²',
    finish: 'Standard',
    motor: specCustom,
    gearbox: 'N/A',
    controls: 'Hydraulic/manual closing',
    features: [
      'Efficient solid-liquid separation',
      'Various plate sizes',
      'Hydraulic closing option',
      'Filter cloth options',
      'Easy cake discharge',
    ],
    industries: ['Pharmaceutical', 'Chemical', 'Specialty Chemicals'],
    images: [
      { src: '/images/products/filter-press.jpg', alt: 'Filter Press' },
    ],
    technicalSpecifications: [
      { parameter: 'Machine Type', specification: 'Filter Press' },
      { parameter: 'Plate Size', specification: 'Various sizes available' },
      { parameter: 'Material of Construction', specification: 'SS 304 / SS 316 / PP' },
      { parameter: 'Operating Pressure', specification: 'Up to 10-15 kg/cm²' },
      { parameter: 'Closing System', specification: 'Hydraulic / Manual' },
    ],
    faq: [],
    seoTitle: 'Filter Press Manufacturer | Pharmaceutical Filter Press | Khushbu Pharma Machinery',
    seoDescription: 'Khushbu Pharma Machinery manufactures Filter Presses for solid-liquid separation in pharmaceutical and chemical industries.',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '18',
    slug: 'vibro-sifter',
    name: 'Vibro Sifter',
    category: 'Filtration & Sifting',
    shortDescription: 'Vibro sifter for screening, grading, and sifting of powders and granules.',
    description: 'The Vibro Sifter from Khushbu Pharma Machinery provides efficient screening and grading of powders, granules, and other materials. Available in single, double, and triple deck configurations.',
    applications: [
      'Screening of pharmaceutical powders',
      'Grading of granules',
      'De-dusting of tablets',
      'Food ingredient sifting',
      'Chemical powder screening',
    ],
    capacity: specNA,
    materialOfConstruction: 'SS 304 / SS 316',
    contactParts: 'SS 316',
    nonContactParts: 'SS 304',
    power: specCustom,
    dimensions: specCustom,
    workingVolume: specNA,
    operatingTemperature: 'Ambient',
    operatingPressure: 'Atmospheric',
    finish: 'Standard / SS finish',
    motor: specCustom,
    gearbox: 'N/A',
    controls: 'ON/OFF',
    features: [
      'Single/double/triple deck options',
      'Various mesh sizes',
      'Easy screen change',
      'Dust-free operation',
      'Continuous operation',
      'High throughput',
    ],
    industries: ['Pharmaceutical', 'Food Processing', 'Chemical', 'Ayurvedic & Herbal'],
    images: [
      { src: '/images/products/vibro-sifter.jpg', alt: 'Vibro Sifter' },
    ],
    technicalSpecifications: [
      { parameter: 'Machine Type', specification: 'Vibro Sifter' },
      { parameter: 'Deck Configuration', specification: 'Single / Double / Triple' },
      { parameter: 'Material of Construction', specification: 'SS 304 / SS 316' },
      { parameter: 'Screen Sizes', specification: 'Various mesh options' },
      { parameter: 'Diameter', specification: 'Various sizes available' },
    ],
    faq: [],
    seoTitle: 'Vibro Sifter Manufacturer | Vibro Sifter Machine | Khushbu Pharma Machinery',
    seoDescription: 'Khushbu Pharma Machinery manufactures Vibro Sifters for screening, grading, and sifting of pharmaceutical powders and granules.',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '19',
    slug: 'auto-coater',
    name: 'Auto Coater',
    category: 'Coating Equipment',
    shortDescription: 'Automatic tablet coating machine with programmable controls for film, sugar, and enteric coating.',
    description: 'The Auto Coater from Khushbu Pharma Machinery is a fully automatic tablet coating system with programmable logic controller (PLC) for precise control of coating parameters. Features include automated spray rate control, pan speed regulation, inlet air temperature management, and exhaust damper control. Designed for uniform film coating, sugar coating, and enteric coating of tablets in pharmaceutical, nutraceutical, and ayurvedic industries.',
    applications: [
      'Film coating of tablets',
      'Sugar coating of tablets',
      'Enteric coating',
      'Sustained release coating',
      'Pellet coating',
      'Color coating',
    ],
    capacity: specNA,
    materialOfConstruction: 'SS 304 / SS 316 / SS 316L',
    contactParts: 'SS 316 / SS 316L',
    nonContactParts: 'SS 304',
    power: specCustom,
    dimensions: specCustom,
    workingVolume: specNA,
    operatingTemperature: 'Up to 120°C inlet air',
    operatingPressure: 'Atmospheric with slight positive pressure',
    finish: 'Mirror polish (pan interior)',
    motor: specCustom,
    gearbox: specCustom,
    controls: 'PLC based with HMI touch screen',
    features: [
      'Fully automatic operation',
      'PLC with HMI touch screen',
      'Programmable coating recipes',
      'Automated spray rate control',
      'Pan speed regulation (VFD)',
      'Inlet air temperature control',
      'Exhaust damper control',
      'Peristaltic pump for coating solution',
      'Spray gun assembly with atomization',
      'GMP compliant design',
      'SS 316L contact parts',
      'Recipe storage and recall',
    ],
    industries: ['Pharmaceutical', 'Nutraceutical', 'Ayurvedic & Herbal'],
    images: [
      { src: '/images/products/auto-coater.jpg', alt: 'Auto Coater - Automatic Tablet Coating Machine' },
    ],
    technicalSpecifications: [
      { parameter: 'Machine Type', specification: 'Auto Coater (Fully Automatic)' },
      { parameter: 'Capacity', specification: specNA },
      { parameter: 'Material of Construction', specification: 'SS 304 / SS 316 / SS 316L' },
      { parameter: 'Contact Parts', specification: 'SS 316L' },
      { parameter: 'Pan Speed', specification: 'Variable (VFD controlled)' },
      { parameter: 'Coating Type', specification: 'Film / Sugar / Enteric / Sustained Release' },
      { parameter: 'Spray System', specification: 'Peristaltic pump with spray guns' },
      { parameter: 'Air Handling', specification: 'Pre-heating, filtering, exhaust control' },
      { parameter: 'Control System', specification: 'PLC with HMI touch screen' },
      { parameter: 'Inlet Air Temperature', specification: 'Up to 120°C' },
    ],
    faq: [
      {
        question: 'What is an Auto Coater?',
        answer: 'An Auto Coater is a fully automatic tablet coating machine used in pharmaceutical manufacturing. It provides precise control over coating parameters including spray rate, pan speed, air temperature, and humidity for uniform film, sugar, or enteric coating.',
      },
      {
        question: 'What types of coating can be done?',
        answer: 'Film coating, sugar coating, enteric coating, sustained release coating, and color coating of tablets and pellets.',
      },
    ],
    seoTitle: 'Auto Coater Manufacturer | Automatic Tablet Coating Machine | Khushbu Pharma Machinery',
    seoDescription: 'Khushbu Pharma Machinery manufactures Auto Coaters with PLC control for pharmaceutical tablet coating. Film, sugar, and enteric coating applications.',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '20',
    slug: 'ointment-plant',
    name: 'Ointment Plant',
    category: 'Liquid Processing',
    shortDescription: 'Complete ointment manufacturing plant with mixing, homogenizing, and filling capabilities.',
    description: 'The Ointment Plant from Khushbu Pharma Machinery is a complete manufacturing solution for ointments, creams, gels, pastes, and semi-solid formulations. The plant includes manufacturing vessel with anchor/paddle agitator, homogenizer, vacuum system, and transfer pumps. Designed for pharmaceutical, cosmetic, and ayurvedic ointment production with GMP compliance.',
    applications: [
      'Pharmaceutical ointment manufacturing',
      'Cream and gel production',
      'Cosmetic cream manufacturing',
      'Ayurvedic ointment preparation',
      'Topical gel manufacturing',
      'Paste preparation',
    ],
    capacity: specNA,
    materialOfConstruction: 'SS 304 / SS 316 / SS 316L',
    contactParts: 'SS 316L',
    nonContactParts: 'SS 304',
    power: specCustom,
    dimensions: specCustom,
    workingVolume: specNA,
    operatingTemperature: 'Up to 80°C',
    operatingPressure: 'Vacuum to atmospheric',
    finish: 'Mirror polish (contact parts)',
    motor: specCustom,
    gearbox: specCustom,
    controls: 'PLC based / Manual panel with temperature and speed controls',
    features: [
      'Complete manufacturing plant',
      'Anchor/paddle agitator for mixing',
      'High-speed homogenizer',
      'Vacuum system for de-aeration',
      'Jacketed vessel for heating/cooling',
      'Transfer pump for product movement',
      'GMP compliant design',
      'SS 316L contact parts',
      'Various capacity options',
    ],
    industries: ['Pharmaceutical', 'Cosmetics', 'Ayurvedic & Herbal'],
    images: [
      { src: '/images/products/ointment-plant.jpg', alt: 'Ointment Manufacturing Plant' },
    ],
    technicalSpecifications: [
      { parameter: 'Machine Type', specification: 'Ointment Manufacturing Plant' },
      { parameter: 'Capacity', specification: specNA },
      { parameter: 'Material of Construction', specification: 'SS 304 / SS 316 / SS 316L' },
      { parameter: 'Contact Parts', specification: 'SS 316L' },
      { parameter: 'Agitator Type', specification: 'Anchor / Paddle / Speed可控' },
      { parameter: 'Homogenizer', specification: 'High-speed rotor-stator type' },
      { parameter: 'Vacuum System', specification: 'For de-aeration' },
      { parameter: 'Heating/Cooling', specification: 'Jacketed (steam/hot water/cold water)' },
      { parameter: 'Control System', specification: 'PLC / Manual' },
    ],
    faq: [
      {
        question: 'What is an Ointment Plant?',
        answer: 'An Ointment Plant is a complete manufacturing system for producing ointments, creams, gels, and semi-solid formulations. It includes mixing, homogenizing, vacuum de-aeration, and transfer capabilities.',
      },
      {
        question: 'What products can be manufactured?',
        answer: 'Pharmaceutical ointments, cosmetic creams, dermatological gels, ayurvedic preparations, topical pastes, and other semi-solid formulations.',
      },
    ],
    seoTitle: 'Ointment Plant Manufacturer | Ointment Manufacturing Plant | Khushbu Pharma Machinery',
    seoDescription: 'Khushbu Pharma Machinery manufactures complete Ointment Plants for pharmaceutical, cosmetic, and ayurvedic ointment and cream manufacturing.',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '21',
    slug: 'liquid-manufacturing-plant',
    name: 'Liquid Manufacturing Plant',
    category: 'Liquid Processing',
    shortDescription: 'Complete liquid manufacturing plant for syrup, suspension, solution, and liquid oral formulations.',
    description: 'The Liquid Manufacturing Plant from Khushbu Pharma Machinery is a complete system for manufacturing liquid oral formulations including syrups, suspensions, solutions, and emulsions. The plant includes manufacturing vessel with high-speed mixer, holding vessel, filtration system, and transfer pumps. Designed for pharmaceutical liquid oral dosage manufacturing with GMP compliance.',
    applications: [
      'Syrup manufacturing',
      'Suspension preparation',
      'Solution manufacturing',
      'Emulsion production',
      'Liquid oral dosage forms',
      'Cosmetic liquid manufacturing',
    ],
    capacity: specNA,
    materialOfConstruction: 'SS 304 / SS 316 / SS 316L',
    contactParts: 'SS 316L',
    nonContactParts: 'SS 304',
    power: specCustom,
    dimensions: specCustom,
    workingVolume: specNA,
    operatingTemperature: 'Up to 80°C',
    operatingPressure: 'Atmospheric',
    finish: 'Mirror polish (contact parts)',
    motor: specCustom,
    gearbox: specCustom,
    controls: 'PLC / Manual panel',
    features: [
      'Complete liquid manufacturing system',
      'High-speed propeller/turbine mixer',
      'Manufacturing vessel with jacket',
      'Holding/storage vessel',
      'Inline filter for clarification',
      'Transfer pump',
      'CIP (Clean-in-Place) provision',
      'GMP compliant design',
      'Various capacity options',
    ],
    industries: ['Pharmaceutical', 'Ayurvedic & Herbal', 'Food Processing'],
    images: [
      { src: '/images/products/liquid-manufacturing-plant.jpg', alt: 'Liquid Manufacturing Plant' },
    ],
    technicalSpecifications: [
      { parameter: 'Machine Type', specification: 'Liquid Manufacturing Plant' },
      { parameter: 'Capacity', specification: specNA },
      { parameter: 'Material of Construction', specification: 'SS 304 / SS 316 / SS 316L' },
      { parameter: 'Contact Parts', specification: 'SS 316L' },
      { parameter: 'Mixer Type', specification: 'High-speed propeller / Turbine' },
      { parameter: 'Heating/Cooling', specification: 'Jacketed vessel' },
      { parameter: 'Filtration', specification: 'Inline basket / cartridge filter' },
      { parameter: 'Transfer', specification: 'Centrifugal / Lobe pump' },
      { parameter: 'CIP', specification: 'Optional' },
    ],
    faq: [
      {
        question: 'What is a Liquid Manufacturing Plant?',
        answer: 'A Liquid Manufacturing Plant is a complete system for producing liquid oral formulations like syrups, suspensions, solutions, and emulsions. It includes mixing, holding, filtration, and transfer capabilities.',
      },
    ],
    seoTitle: 'Liquid Manufacturing Plant Manufacturer | Pharma Liquid Plant | Khushbu Pharma Machinery',
    seoDescription: 'Khushbu Pharma Machinery manufactures complete Liquid Manufacturing Plants for pharmaceutical syrup, suspension, and solution manufacturing.',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '22',
    slug: 'sugar-melting-tank',
    name: 'Sugar Melting Tank',
    category: 'Liquid Processing',
    shortDescription: 'Sugar melting tank with agitation and heating for pharmaceutical syrup manufacturing.',
    description: 'The Sugar Melting Tank from Khushbu Pharma Machinery is designed for efficient melting and dissolution of sugar in water for pharmaceutical syrup manufacturing. Features include jacketed heating, high-speed agitation, and temperature control. Available in various capacities for batch to continuous operations.',
    applications: [
      'Sugar melting for syrup manufacturing',
      'Sugar solution preparation',
      'Pharmaceutical syrup production',
      'Confectionery sugar dissolution',
      'Chemical solution preparation',
    ],
    capacity: specNA,
    materialOfConstruction: 'SS 304 / SS 316 / SS 316L',
    contactParts: 'SS 316 / SS 316L',
    nonContactParts: 'SS 304',
    power: specCustom,
    dimensions: specCustom,
    workingVolume: specNA,
    operatingTemperature: 'Up to 100°C',
    operatingPressure: 'Atmospheric',
    finish: 'Mirror polish (contact parts)',
    motor: specCustom,
    gearbox: specCustom,
    controls: 'Temperature controller with timer',
    features: [
      'Jacketed heating (steam/hot water)',
      'High-speed propeller agitator',
      'Temperature control system',
      'Manhole for cleaning',
      'Product outlet with valve',
      'GMP compliant design',
      'Various capacity options',
    ],
    industries: ['Pharmaceutical', 'Ayurvedic & Herbal', 'Food Processing'],
    images: [
      { src: '/images/products/sugar-melting-tank.jpg', alt: 'Sugar Melting Tank' },
    ],
    technicalSpecifications: [
      { parameter: 'Machine Type', specification: 'Sugar Melting Tank' },
      { parameter: 'Capacity', specification: specNA },
      { parameter: 'Material of Construction', specification: 'SS 304 / SS 316 / SS 316L' },
      { parameter: 'Heating', specification: 'Jacketed (steam/hot water)' },
      { parameter: 'Agitation', specification: 'High-speed propeller' },
      { parameter: 'Temperature Control', specification: 'Digital temperature controller' },
    ],
    faq: [],
    seoTitle: 'Sugar Melting Tank Manufacturer | Pharma Sugar Tank | Khushbu Pharma Machinery',
    seoDescription: 'Khushbu Pharma Machinery manufactures Sugar Melting Tanks for pharmaceutical syrup manufacturing with jacketed heating and agitation.',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '23',
    slug: 'coating-pan-hot-air',
    name: 'Coating Pan with Hot Air Blower',
    category: 'Coating Equipment',
    shortDescription: 'Coating pan with integrated hot air blower system for efficient tablet coating and drying.',
    description: 'The Coating Pan with Hot Air Blower from Khushbu Pharma Machinery combines the coating pan with an integrated hot air system for simultaneous coating and drying. The hot air blower provides heated air to the pan surface for rapid drying of coating solution, ensuring uniform and efficient coating. Ideal for sugar coating, film coating, and color coating of tablets.',
    applications: [
      'Sugar coating of tablets',
      'Film coating',
      'Color coating',
      'Enteric coating',
      'Pellet coating',
    ],
    capacity: specNA,
    materialOfConstruction: 'SS 304 / SS 316',
    contactParts: 'SS 316',
    nonContactParts: 'SS 304',
    power: specCustom,
    dimensions: specCustom,
    workingVolume: specNA,
    operatingTemperature: 'Ambient to 80°C',
    operatingPressure: 'Atmospheric',
    finish: 'Mirror polish (pan interior)',
    motor: specCustom,
    gearbox: specCustom,
    controls: 'Variable speed for pan rotation, hot air temperature control',
    features: [
      'Integrated hot air blower',
      'Simultaneous coating and drying',
      'Adjustable pan speed',
      'Temperature controlled hot air',
      'Spray gun provision',
      'Various pan sizes',
      'GMP compliant',
    ],
    industries: ['Pharmaceutical', 'Nutraceutical', 'Ayurvedic & Herbal'],
    images: [
      { src: '/images/products/coating-pan-hot-air.jpg', alt: 'Coating Pan with Hot Air Blower' },
    ],
    technicalSpecifications: [
      { parameter: 'Machine Type', specification: 'Coating Pan with Hot Air Blower' },
      { parameter: 'Capacity', specification: specNA },
      { parameter: 'Material of Construction', specification: 'SS 304 / SS 316' },
      { parameter: 'Pan Speed', specification: 'Variable (VFD)' },
      { parameter: 'Hot Air Temperature', specification: 'Up to 80°C' },
      { parameter: 'Blower', specification: 'Centrifugal type with heater' },
    ],
    faq: [],
    seoTitle: 'Coating Pan with Hot Air Blower | Tablet Coating Machine | Khushbu Pharma Machinery',
    seoDescription: 'Khushbu Pharma Machinery manufactures Coating Pans with integrated Hot Air Blower for efficient tablet coating and drying.',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '24',
    slug: 'autoclave',
    name: 'Autoclave',
    category: 'Sterilization',
    shortDescription: 'Steam sterilization autoclave for pharmaceutical, laboratory, and healthcare applications.',
    description: 'The Autoclave from Khushbu Pharma Machinery is designed for reliable steam sterilization of equipment, components, tools, and materials in pharmaceutical, laboratory, and healthcare applications. Features include programmable cycle selection, temperature and pressure monitoring, and safety interlocks. Available in horizontal, vertical, and jacketed configurations.',
    applications: [
      'Sterilization of pharmaceutical equipment',
      'Sterilization of laboratory glassware',
      'Sterilization of components and tools',
      'Media sterilization',
      'Sterilization of surgical instruments',
      'Depyrogenation',
    ],
    capacity: specNA,
    materialOfConstruction: 'SS 304 / SS 316 / SS 316L',
    contactParts: 'SS 316 / SS 316L',
    nonContactParts: 'SS 304',
    power: specCustom,
    dimensions: specCustom,
    workingVolume: specNA,
    operatingTemperature: 'Up to 134°C',
    operatingPressure: 'Up to 2.2 kg/cm²',
    finish: 'Mirror polish (chamber)',
    motor: 'N/A',
    gearbox: 'N/A',
    controls: 'PLC / Microprocessor based with digital display',
    features: [
      'Steam sterilization',
      'Programmable cycle selection',
      'Temperature and pressure monitoring',
      'Safety interlocks',
      'Door locking mechanism',
      'Printer/data logger option',
      'GMP compliant design',
      'Various chamber sizes',
    ],
    industries: ['Pharmaceutical', 'Laboratory', 'Healthcare'],
    images: [
      { src: '/images/products/autoclave.jpg', alt: 'Autoclave - Steam Sterilization' },
    ],
    technicalSpecifications: [
      { parameter: 'Machine Type', specification: 'Autoclave (Steam Sterilizer)' },
      { parameter: 'Chamber Size', specification: 'Various sizes available' },
      { parameter: 'Material of Construction', specification: 'SS 316L (chamber)' },
      { parameter: 'Operating Temperature', specification: 'Up to 134°C' },
      { parameter: 'Operating Pressure', specification: 'Up to 2.2 kg/cm²' },
      { parameter: 'Sterilization Cycle', specification: 'Gravity / Pre-vacuum / Liquid' },
      { parameter: 'Control System', specification: 'PLC / Microprocessor' },
      { parameter: 'Safety Features', specification: 'Door interlock, pressure relief, over-temp alarm' },
    ],
    faq: [
      {
        question: 'What is an Autoclave used for?',
        answer: 'An Autoclave is used for steam sterilization of equipment, components, glassware, and materials in pharmaceutical manufacturing, laboratories, and healthcare facilities.',
      },
    ],
    seoTitle: 'Autoclave Manufacturer | Steam Sterilizer | Khushbu Pharma Machinery',
    seoDescription: 'Khushbu Pharma Machinery manufactures Autoclaves for steam sterilization in pharmaceutical, laboratory, and healthcare applications.',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '25',
    slug: 'lifting-chamber-ibc',
    name: 'Lifting Chamber with IBC Bin',
    category: 'Material Handling',
    shortDescription: 'Lifting and transfer chamber with IBC bin for dust-free material handling in pharmaceutical manufacturing.',
    description: 'The Lifting Chamber with IBC Bin from Khushbu Pharma Machinery is designed for safe and dust-free transfer of powders and granules between process equipment. The system includes a hydraulic lifting mechanism, containment chamber, and IBC (Intermediate Bulk Container) bin for material storage and transfer. Essential for maintaining GMP compliance and operator safety during material handling.',
    applications: [
      'Powder transfer between equipment',
      'Granule transfer to tablet press',
      'Dust-free material loading',
      'IBC bin charging and discharging',
      'Contained material handling',
      'FBD to RMG transfer',
    ],
    capacity: specNA,
    materialOfConstruction: 'SS 304 / SS 316 / SS 316L',
    contactParts: 'SS 316L',
    nonContactParts: 'SS 304',
    power: specCustom,
    dimensions: specCustom,
    workingVolume: specNA,
    operatingTemperature: 'Ambient',
    operatingPressure: 'Atmospheric',
    finish: 'Mirror polish (contact parts)',
    motor: specCustom,
    gearbox: 'N/A',
    controls: 'Hydraulic controls with limit switches',
    features: [
      'Hydraulic lifting mechanism',
      'Dust-free contained transfer',
      'IBC bin compatibility',
      'Various bin sizes',
      'Safety interlocks',
      'GMP compliant design',
      'SS 316L contact parts',
      'Easy cleaning and maintenance',
    ],
    industries: ['Pharmaceutical', 'Chemical', 'Food Processing'],
    images: [
      { src: '/images/products/lifting-chamber.jpg', alt: 'Lifting Chamber with IBC Bin' },
    ],
    technicalSpecifications: [
      { parameter: 'Machine Type', specification: 'Lifting Chamber with IBC Bin' },
      { parameter: 'Capacity', specification: specNA },
      { parameter: 'Material of Construction', specification: 'SS 304 / SS 316 / SS 316L' },
      { parameter: 'Lifting Mechanism', specification: 'Hydraulic' },
      { parameter: 'IBC Bin Size', specification: 'Various sizes available' },
      { parameter: 'Bin Material', specification: 'SS 304 / SS 316' },
      { parameter: 'Containment', specification: 'Dust-tight seal' },
    ],
    faq: [],
    seoTitle: 'Lifting Chamber with IBC Bin | Material Handling Equipment | Khushbu Pharma Machinery',
    seoDescription: 'Khushbu Pharma Machinery manufactures Lifting Chambers with IBC Bins for dust-free powder and granule transfer in pharmaceutical manufacturing.',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '26',
    slug: 'v-blender',
    name: 'V Blender',
    category: 'Blenders',
    shortDescription: 'V-shaped blender for efficient blending of dry powders, granules, and tablets.',
    description: 'The V Blender from Khushbu Pharma Machinery features a V-shaped shell that provides excellent blending efficiency through tumbling action. The unique geometry ensures uniform mixing of dry powders, granules, and even coated tablets with minimal product degradation. Ideal for pharmaceutical, food, and chemical applications.',
    applications: [
      'Blending of pharmaceutical powders',
      'Mixing of granules and pellets',
      'Gentle handling of coated tablets',
      'Food ingredient blending',
      'Chemical powder mixing',
    ],
    capacity: specNA,
    materialOfConstruction: 'SS 304 / SS 316 / SS 316L',
    contactParts: 'SS 316 / SS 316L',
    nonContactParts: 'SS 304',
    power: specCustom,
    dimensions: specCustom,
    workingVolume: specNA,
    operatingTemperature: 'Ambient',
    operatingPressure: 'Atmospheric',
    finish: 'Mirror polish',
    motor: specCustom,
    gearbox: specCustom,
    controls: 'VFD based speed control',
    features: [
      'V-shaped geometry for superior blending',
      'Tumbling action for uniform mixing',
      'Gentle on product',
      'Easy to clean',
      'GMP compliant design',
      'Variable speed control',
      'Safety interlocks',
    ],
    industries: ['Pharmaceutical', 'Food Processing', 'Nutraceutical', 'Chemical'],
    images: [
      { src: '/images/products/v-blender.jpg', alt: 'V Blender' },
    ],
    technicalSpecifications: [
      { parameter: 'Machine Type', specification: 'V Blender' },
      { parameter: 'Capacity', specification: specNA },
      { parameter: 'Material of Construction', specification: 'SS 304 / SS 316 / SS 316L' },
      { parameter: 'Contact Parts', specification: 'SS 316 / SS 316L' },
      { parameter: 'Geometry', specification: 'V-shaped shell' },
      { parameter: 'Speed Control', specification: 'VFD' },
      { parameter: 'Surface Finish', specification: 'Mirror polish' },
    ],
    faq: [
      {
        question: 'What is a V Blender?',
        answer: 'A V Blender is a type of tumble blender with a V-shaped shell that provides excellent blending efficiency through tumbling action. It is widely used in pharmaceutical, food, and chemical industries for uniform mixing of dry powders and granules.',
      },
    ],
    seoTitle: 'V Blender Manufacturer | V-Shape Blender | Khushbu Pharma Machinery',
    seoDescription: 'Khushbu Pharma Machinery manufactures V Blenders for efficient blending of pharmaceutical powders, granules, and tablets.',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '27',
    slug: 'rnd-lab-fbd',
    name: 'R&D Lab Scale FBD',
    category: 'R&D / Lab Equipment',
    shortDescription: 'Laboratory scale fluid bed dryer for R&D, formulation development, and pilot scale studies.',
    description: 'The R&D Lab Scale FBD from Khushbu Pharma Machinery is a compact fluid bed dryer designed for laboratory use, formulation development, and pilot scale studies. Small batch capacity allows researchers to optimize process parameters before scaling up to production. Features include precise temperature control, adjustable air flow, and easy change of product containers.',
    applications: [
      'Formulation development',
      'Process optimization studies',
      'Pilot scale trials',
      'Lab scale drying',
      'Research and development',
      'Feasibility studies',
    ],
    capacity: '1 kg to 10 kg (lab scale)',
    materialOfConstruction: 'SS 316L / SS 316',
    contactParts: 'SS 316L',
    nonContactParts: 'SS 304',
    power: specCustom,
    dimensions: 'Compact bench-top / floor standing',
    workingVolume: '1-10 kg',
    operatingTemperature: 'Ambient to 120°C',
    operatingPressure: 'Atmospheric',
    finish: 'Mirror polish',
    motor: specCustom,
    gearbox: 'N/A',
    controls: 'PLC / Manual with digital display',
    features: [
      'Lab scale capacity (1-10 kg)',
      'Precise temperature control',
      'Adjustable air flow',
      'Easy product container change',
      'Quick disassembly for cleaning',
      'Process data logging',
      'Scale-up data correlation',
      'Compact footprint',
    ],
    industries: ['Pharmaceutical', 'Research & Development'],
    images: [
      { src: '/images/products/rnd-lab-fbd.jpg', alt: 'R&D Lab Scale Fluid Bed Dryer' },
    ],
    technicalSpecifications: [
      { parameter: 'Machine Type', specification: 'R&D Lab Scale FBD' },
      { parameter: 'Batch Capacity', specification: '1 kg to 10 kg' },
      { parameter: 'Material of Construction', specification: 'SS 316L (contact) / SS 304' },
      { parameter: 'Air Flow', specification: 'Adjustable (VFD)' },
      { parameter: 'Temperature Range', specification: 'Ambient to 120°C' },
      { parameter: 'Filtration', specification: 'Bag filter + HEPA' },
      { parameter: 'Footprint', specification: 'Compact bench-top / floor standing' },
    ],
    faq: [],
    seoTitle: 'R&D Lab Scale FBD | Laboratory Fluid Bed Dryer | Khushbu Pharma Machinery',
    seoDescription: 'Khushbu Pharma Machinery manufactures R&D Lab Scale Fluid Bed Dryers for pharmaceutical formulation development and pilot studies.',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '28',
    slug: 'rnd-lab-rmg',
    name: 'R&D Lab Scale RMG',
    category: 'R&D / Lab Equipment',
    shortDescription: 'Laboratory scale rapid mixing granulator for R&D and formulation development.',
    description: 'The R&D Lab Scale RMG from Khushbu Pharma Machinery is a compact rapid mixing granulator designed for laboratory use and formulation development. Small batch capacity allows researchers to develop and optimize granulation processes before scaling up. Features include variable impeller and chopper speed, and easy bowl removal for cleaning.',
    applications: [
      'Wet granulation development',
      'Formulation optimization',
      'Lab scale granulation',
      'Process parameter studies',
      'Research and development',
    ],
    capacity: '1 kg to 10 kg (lab scale)',
    materialOfConstruction: 'SS 316L / SS 316',
    contactParts: 'SS 316L',
    nonContactParts: 'SS 304',
    power: specCustom,
    dimensions: 'Compact bench-top',
    workingVolume: '1-10 kg',
    operatingTemperature: 'Ambient',
    operatingPressure: 'Atmospheric',
    finish: 'Mirror polish',
    motor: specCustom,
    gearbox: specCustom,
    controls: 'VFD based with digital display',
    features: [
      'Lab scale capacity (1-10 kg)',
      'Variable impeller speed',
      'Variable chopper speed',
      'Easy bowl removal',
      'Quick disassembly for cleaning',
      'Process parameter recording',
      'Scale-up capability',
      'Compact design',
    ],
    industries: ['Pharmaceutical', 'Research & Development'],
    images: [
      { src: '/images/products/rnd-lab-rmg.jpg', alt: 'R&D Lab Scale Rapid Mixing Granulator' },
    ],
    technicalSpecifications: [
      { parameter: 'Machine Type', specification: 'R&D Lab Scale RMG' },
      { parameter: 'Batch Capacity', specification: '1 kg to 10 kg' },
      { parameter: 'Material of Construction', specification: 'SS 316L (contact) / SS 304' },
      { parameter: 'Impeller', specification: 'Variable speed (VFD)' },
      { parameter: 'Chopper', specification: 'Variable speed (VFD)' },
      { parameter: 'Bowl', specification: 'Removable for cleaning' },
    ],
    faq: [],
    seoTitle: 'R&D Lab Scale RMG | Laboratory Rapid Mixing Granulator | Khushbu Pharma Machinery',
    seoDescription: 'Khushbu Pharma Machinery manufactures R&D Lab Scale Rapid Mixing Granulators for pharmaceutical formulation development.',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '29',
    slug: 'rnd-mini-tablet-press',
    name: 'R&D Mini Tablet Press',
    category: 'R&D / Lab Equipment',
    shortDescription: 'Mini rotary tablet press for R&D, formulation trials, and small batch production.',
    description: 'The R&D Mini Tablet Press from Khushbu Pharma Machinery is a compact rotary tablet press designed for laboratory use, formulation trials, and small batch production. Features include variable tablet weight control, easy tooling change, and force monitoring for consistent tablet quality. Ideal for pharmaceutical R&D labs and pilot plants.',
    applications: [
      'Tablet formulation development',
      'R&D tablet compression',
      'Small batch production',
      'Tooling trials',
      'Process optimization',
    ],
    capacity: 'Up to 10,000 tablets/hour (lab scale)',
    materialOfConstruction: 'SS 316 / Tooling steel',
    contactParts: 'SS 316',
    nonContactParts: 'SS 304',
    power: specCustom,
    dimensions: 'Compact bench-top',
    workingVolume: '5-20 tablets per stroke',
    operatingTemperature: 'Ambient',
    operatingPressure: 'Atmospheric',
    finish: 'Mirror polish / Hard chrome',
    motor: specCustom,
    gearbox: specCustom,
    controls: 'Variable speed with tablet weight adjustment',
    features: [
      'Lab/pilot scale capacity',
      'Variable tablet weight',
      'Easy tooling change',
      'Force monitoring system',
      'Turret speed adjustment',
      'Hopper for powder feed',
      'Dedusting provision',
      'Compact design',
    ],
    industries: ['Pharmaceutical', 'Research & Development'],
    images: [
      { src: '/images/products/rnd-mini-tablet-press.jpg', alt: 'R&D Mini Tablet Press' },
    ],
    technicalSpecifications: [
      { parameter: 'Machine Type', specification: 'R&D Mini Tablet Press' },
      { parameter: 'Output', specification: 'Up to 10,000 tablets/hour' },
      { parameter: 'Tooling', specification: 'B/D type (standard)' },
      { parameter: 'Tablet Diameter', specification: '5-20 mm' },
      { parameter: 'Turret Speed', specification: 'Variable (VFD)' },
      { parameter: 'Force Monitoring', specification: 'Pre and main compression' },
    ],
    faq: [],
    seoTitle: 'R&D Mini Tablet Press | Lab Tablet Press | Khushbu Pharma Machinery',
    seoDescription: 'Khushbu Pharma Machinery manufactures R&D Mini Tablet Presses for pharmaceutical formulation development and small batch production.',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '30',
    slug: 'rnd-lab-coating-pan',
    name: 'R&D Lab Coating Pan',
    category: 'R&D / Lab Equipment',
    shortDescription: 'Laboratory scale coating pan for formulation development and coating trials.',
    description: 'The R&D Lab Coating Pan from Khushbu Pharma Machinery is a compact coating system designed for laboratory use and formulation development. Small batch capacity allows researchers to develop and optimize coating processes before scaling up. Features include adjustable pan speed, spray system, and temperature control.',
    applications: [
      'Coating formulation development',
      'Lab scale tablet coating',
      'Pellet coating trials',
      'Process optimization',
      'Research and development',
    ],
    capacity: '0.5 kg to 5 kg (lab scale)',
    materialOfConstruction: 'SS 316 / SS 316L',
    contactParts: 'SS 316L',
    nonContactParts: 'SS 304',
    power: specCustom,
    dimensions: 'Compact bench-top',
    workingVolume: '0.5-5 kg',
    operatingTemperature: 'Ambient to 80°C',
    operatingPressure: 'Atmospheric',
    finish: 'Mirror polish',
    motor: specCustom,
    gearbox: specCustom,
    controls: 'Variable speed, temperature control',
    features: [
      'Lab scale capacity (0.5-5 kg)',
      'Adjustable pan speed',
      'Peristaltic pump for coating solution',
      'Hot air provision',
      'Spray gun with atomization',
      'Easy cleaning',
      'Process parameter recording',
    ],
    industries: ['Pharmaceutical', 'Research & Development'],
    images: [
      { src: '/images/products/rnd-lab-coating-pan.jpg', alt: 'R&D Lab Coating Pan' },
    ],
    technicalSpecifications: [
      { parameter: 'Machine Type', specification: 'R&D Lab Coating Pan' },
      { parameter: 'Batch Capacity', specification: '0.5 kg to 5 kg' },
      { parameter: 'Pan Diameter', specification: '12" to 18"' },
      { parameter: 'Pan Speed', specification: 'Variable (VFD)' },
      { parameter: 'Spray System', specification: 'Peristaltic pump + spray gun' },
      { parameter: 'Hot Air', specification: 'Optional with temperature control' },
    ],
    faq: [],
    seoTitle: 'R&D Lab Coating Pan | Laboratory Coating Pan | Khushbu Pharma Machinery',
    seoDescription: 'Khushbu Pharma Machinery manufactures R&D Lab Coating Pans for pharmaceutical formulation development and coating trials.',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '31',
    slug: 'rnd-lab-multi-mill',
    name: 'R&D Lab Multi Mill',
    category: 'R&D / Lab Equipment',
    shortDescription: 'Laboratory scale multi mill for R&D grinding, mixing, and size reduction.',
    description: 'The R&D Lab Multi Mill from Khushbu Pharma Machinery is a compact grinding and mixing machine designed for laboratory use. Small capacity allows researchers to study size reduction characteristics and optimize process parameters. Features include various screen options, easy screen change, and variable speed control.',
    applications: [
      'Lab scale grinding',
      'Size reduction studies',
      'Herb and spice grinding trials',
      'Process optimization',
      'Research and development',
    ],
    capacity: '5 kg to 25 kg/hour (lab scale)',
    materialOfConstruction: 'SS 316 / SS 316L',
    contactParts: 'SS 316L',
    nonContactParts: 'SS 304',
    power: specCustom,
    dimensions: 'Compact bench-top',
    workingVolume: '5-25 kg/hr',
    operatingTemperature: 'Ambient',
    operatingPressure: 'Atmospheric',
    finish: 'Mirror polish',
    motor: specCustom,
    gearbox: 'N/A',
    controls: 'Variable speed with overload protection',
    features: [
      'Lab scale capacity',
      'Various screen options',
      'Easy screen change',
      'Variable speed control',
      'Swinging beaters',
      'Dust collection provision',
      'Compact design',
    ],
    industries: ['Pharmaceutical', 'Ayurvedic & Herbal', 'Research & Development'],
    images: [
      { src: '/images/products/rnd-lab-multi-mill.jpg', alt: 'R&D Lab Multi Mill' },
    ],
    technicalSpecifications: [
      { parameter: 'Machine Type', specification: 'R&D Lab Multi Mill' },
      { parameter: 'Output', specification: '5-25 kg/hour' },
      { parameter: 'Material of Construction', specification: 'SS 316L (contact) / SS 304' },
      { parameter: 'Screens', specification: 'Various mesh options' },
      { parameter: 'Speed', specification: 'Variable (VFD)' },
      { parameter: 'Beaters', specification: 'Swinging type with scrapper' },
    ],
    faq: [],
    seoTitle: 'R&D Lab Multi Mill | Laboratory Multi Mill | Khushbu Pharma Machinery',
    seoDescription: 'Khushbu Pharma Machinery manufactures R&D Lab Multi Mills for pharmaceutical laboratory grinding and size reduction.',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find(p => p.slug === slug);
}

export function getProductsByCategory(categorySlug: string): Product[] {
  const category = categories.find(c => c.slug === categorySlug);
  if (!category) return [];
  return products.filter(p => category.products.includes(p.slug));
}

export function getProductsByIndustry(industrySlug: string): Product[] {
  const industry = industriesData.find(i => i.slug === industrySlug);
  if (!industry) return [];
  return products.filter(p => industry.relevantProducts.includes(p.slug));
}

export function searchProducts(query: string): Product[] {
  const lowerQuery = query.toLowerCase();
  return products.filter(p =>
    p.name.toLowerCase().includes(lowerQuery) ||
    p.category.toLowerCase().includes(lowerQuery) ||
    p.shortDescription.toLowerCase().includes(lowerQuery) ||
    p.applications.some(a => a.toLowerCase().includes(lowerQuery)) ||
    p.industries.some(i => i.toLowerCase().includes(lowerQuery))
  );
}

export function getRelatedProducts(productSlug: string, limit = 4): Product[] {
  const product = getProductBySlug(productSlug);
  if (!product) return [];
  return products
    .filter(p => p.slug !== productSlug && (p.category === product.category || p.industries.some(i => product.industries.includes(i))))
    .slice(0, limit);
}
